
######### the first args is output file generated by cal_slope_cattss3.R script

options(stringsAsFactors = FALSE)
options(scipen = 100)

args=commandArgs(T)




peak <- read.csv(args[1])

infantom <- read.table("temp_tss_in_FANTOM.bed")

infantom <- unique(data.frame(infantom[,c(1,2,3,4,6)],isindsc=1))

colnames(infantom)[c(1,2,3,4,5)] <- c("chr","peak_start","peak_end","gene","strand")

peak <- merge(peak,infantom,all = T,by = c("chr","peak_start","peak_end","gene","strand"))

peak[is.na(peak)] <- 0

peak <- data.frame(peak[,1:6],
                   dominant_tss_position=peak[,3],
                   peak[,7:15])
colnames(peak)[11] <- "dominant_tss_RPM/smart_seq2_RPM"

write.csv(peak,paste(args[1],".csv",sep=""),quote = F,row.names = F)
