####### the first agrs is output file generated by  cal_slope_cattes.R
####### the first agrs is wig file form smart-seq2 data

options(stringsAsFactors = FALSE)
options(scipen = 100)

args=commandArgs(T)

library(rlist)
library(parallel)

memory.limit()
memory.size()

wig <- read.table(args[2])


mm10_chr <- read.table("~/zjw/20190627Parseq/mm10.chrom.sizes")
tc <- read.csv(args[1])

wig_temp <- data.frame()


wig <- rbind(wig,data.frame(V1="variableStep",V2="chrom=ERCC-99999"))
a <- grep("variableStep",wig[,1])

print(a)

for(i in 1:(length(a)-1)) {
  wig_temp <- rbind(wig_temp,
                    data.frame(V1=strsplit(wig[a[i],2],split="=")[[1]][2],wig[(a[i]+1):(a[i+1]-1),]))
}


wig_temp <- wig_temp[!wig_temp[,2]=="variableStep",]

wig_temp[,2] <- as.numeric(wig_temp[,2])
wig_temp[,3] <- as.numeric(wig_temp[,3])

print("region start")

region <- c()
for(i in 1:nrow(tc)) {
  region <- c(region,(tc[i,7]-70):(tc[i,7]+70))
}

region <- unique(region)

print("region middle")

wig_temp <- wig_temp[wig_temp[,2] %in% region,]


print("region done")

print(head(wig_temp))



slope <- function(tc) {
  if(tc[5]=="+") {
    temp <- wig_temp[wig_temp[,1]==tc[2] & wig_temp[,2] %in% (as.numeric(tc[7])-49):as.numeric(tc[7]),]
    zero <- setdiff((as.numeric(tc[7])-49):as.numeric(tc[7]),temp[,2])
    if(!length(zero)==0) {
      temp <- rbind(temp,
                    data.frame(V1=tc[2],V1.1=zero,V2=0))
    }
    temp <- temp[order(temp[,2]),]
    #print(temp)
    #print(" ")
    data.frame(slope=(temp[50,3]-temp[1,3])/50,correlation=cor(temp[,2],temp[,3]))
  } else {
    temp <- wig_temp[wig_temp[,1]==tc[2] & wig_temp[,2] %in% as.numeric(tc[7]):(as.numeric(tc[7])+49),]
    zero <- setdiff(as.numeric(tc[7]):(as.numeric(tc[7])+49),temp[,2])
    if(!length(zero)==0) {
      temp <- rbind(temp,
                    data.frame(V1=tc[2],V1.1=zero,V2=0))
    }
    temp <- temp[order(temp[,2]),]
    #print(temp)
    #print(" ")
    data.frame(slope=(temp[1,3]-temp[50,3])/50,correlation=(-cor(temp[,2],temp[,3])))
  }
}

cl <- makeCluster(5, type = "FORK")
print("START")


test <- parApply(cl,tc,1,slope)


tc_new <- list.rbind(test)



tc_new <- cbind(tc,tc_new)

write.csv(tc_new,paste(args[1],"new.csv",sep=""),quote = F,row.names = F)



print("done")
