if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager", Ncpus=20, repos="https://cran.rstudio.com/")
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools", Ncpus=20, repos="https://cran.rstudio.com/")
if (!requireNamespace("basicTrendline", quietly = TRUE))
    BiocManager::install("basicTrendline", Ncpus=20, update = F, ask = F)
if (!requireNamespace("broom", quietly = TRUE))
    BiocManager::install("broom", Ncpus=20, update = F, ask = F)
if (!requireNamespace("BSgenome", quietly = TRUE))
    BiocManager::install("BSgenome", Ncpus=20, update = F, ask = F)
if (!requireNamespace("BSgenome.Mmusculus.UCSC.mm10", quietly = TRUE))
    BiocManager::install("BSgenome.Mmusculus.UCSC.mm10", Ncpus=20, update = F, ask = F)
if (!requireNamespace("BSgenome.Hsapiens.UCSC.hg38", quietly = TRUE))
    BiocManager::install("BSgenome.Hsapiens.UCSC.hg38", Ncpus=20, update = F, ask = F)
if (!requireNamespace("CAGEr", quietly = TRUE))
    BiocManager::install("CAGEr", Ncpus=20, update = F, ask = F)
if (!requireNamespace("data.table", quietly = TRUE))
    BiocManager::install("data.table", Ncpus=20, update = F, ask = F)
if (!requireNamespace("DESeq2", quietly = TRUE))
    BiocManager::install("DESeq2", Ncpus=20, update = F, ask = F)
if (!requireNamespace("dplyr", quietly = TRUE))
    BiocManager::install("dplyr", Ncpus=20, update = F, ask = F)
if (!requireNamespace("genefilter", quietly = TRUE))
    BiocManager::install("genefilter", Ncpus=20, update = F, ask = F)
if (!requireNamespace("ggalt", quietly = TRUE))
    BiocManager::install("ggalt", Ncpus=20, update = F, ask = F)
if (!requireNamespace("ggplot2", quietly = TRUE))
    BiocManager::install("ggplot2", Ncpus=20, update = F, ask = F)
if (!requireNamespace("ggpubr", quietly = TRUE))
    BiocManager::install("ggpubr", Ncpus=20, update = F, ask = F)
if (!requireNamespace("ggsignif", quietly = TRUE))
    BiocManager::install("ggsignif", Ncpus=20, update = F, ask = F)
if (!requireNamespace("gplots", quietly = TRUE))
    BiocManager::install("gplots", Ncpus=20, update = F, ask = F)
if (!requireNamespace("gridExtra", quietly = TRUE))
    BiocManager::install("gridExtra", Ncpus=20, update = F, ask = F)
if (!requireNamespace("heatmap.plus", quietly = TRUE))
    BiocManager::install("heatmap.plus", Ncpus=20, update = F, ask = F)
if (!requireNamespace("monocle", quietly = TRUE))
    BiocManager::install("monocle", Ncpus=20, update = F, ask = F)
if (!requireNamespace("nlstools", quietly = TRUE))
    BiocManager::install("nlstools", Ncpus=20, update = F, ask = F)
if (!requireNamespace("pheatmap", quietly = TRUE))
    BiocManager::install("pheatmap", Ncpus=20, update = F, ask = F)
if (!requireNamespace("purrr", quietly = TRUE))
    BiocManager::install("purrr", Ncpus=20, update = F, ask = F)
if (!requireNamespace("RColorBrewer", quietly = TRUE))
    BiocManager::install("RColorBrewer", Ncpus=20, update = F, ask = F)
if (!requireNamespace("reshape", quietly = TRUE))
    BiocManager::install("reshape", Ncpus=20, update = F, ask = F)
if (!requireNamespace("rlist", quietly = TRUE))
    BiocManager::install("rlist", Ncpus=20, update = F, ask = F)
if (!requireNamespace("Rmisc", quietly = TRUE))
    BiocManager::install("Rmisc", Ncpus=20, update = F, ask = F)
if (!requireNamespace("rsample", quietly = TRUE))
    BiocManager::install("rsample", Ncpus=20, update = F, ask = F)
if (!requireNamespace("rstatix", quietly = TRUE))
    BiocManager::install("rstatix", Ncpus=20, update = F, ask = F)
if (!requireNamespace("scales", quietly = TRUE))
    BiocManager::install("scales", Ncpus=20, update = F, ask = F)
if (!requireNamespace("splines", quietly = TRUE))
    BiocManager::install("splines", Ncpus=20, update = F, ask = F)
if (!requireNamespace("statmod", quietly = TRUE))
    BiocManager::install("statmod", Ncpus=20, update = F, ask = F)
if (!requireNamespace("stringr", quietly = TRUE))
    BiocManager::install("stringr", Ncpus=20, update = F, ask = F)
if (!requireNamespace("Seurat", quietly = TRUE))
    BiocManager::install("Seurat", Ncpus=20, update = F, ask = F)
if (!requireNamespace("BuenColors", quietly = TRUE))
    BiocManager::install("caleblareau/BuenColors", ask=F, update=F)
