#!/bin/bash


fa_file=$1
fq_file1=$2
fq_file2=$3
star_dir=$4




## Check whether variables are enough
if [[ ! -n "$fa_file" || ! -n "$star_dir" || ! -n "$fq_file1" || ! -n "$fq_file2" ]]; then
    echo "Error: no enough variable!
This script is used to  process the data generated by scCAT-seq in 10x platform. Fastq file is needed and the output file format is BED.
Usage:
    sh $0 <genome fa file> <fastq file R1> <fastq file R2> <STAR index> 
    # Caution: file in <fastq file dir> must be fastq type, not fastq.gz! Pair-end files are needed!
    "
    exit
fi

mkdir outdir/
mkdir outdir/five_prime/
mkdir outdir/five_prime/fastq/
mkdir outdir/five_prime/5cap_read_with_tag/
mkdir outdir/five_prime/trim_TSO/
mkdir outdir/five_prime/mapping_outdir/
mkdir outdir/five_prime/final_out/
mkdir outdir/five_prime/annote/
mkdir outdir/five_prime/collapse/


cp ${fq_file1} outdir/five_prime/fastq/
cp ${fq_file2} outdir/five_prime/fastq/

filetype=${fq_file1##*.}


if [ ${filetype} = "fq" -o ${filetype} = "fastq" ]; then
        echo "unzipped"
else
        gzip -d outdir/five_prime/fastq/*
fi


## 1. Find reads with TSO prime

for i in `ls outdir/five_prime/fastq/|grep "R1"`
do
	cat outdir/five_prime/fastq/${i} | paste - - - - | grep -E $'\t''[A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G][A|T|C|G]TTTC' | awk -v FS="\t" -v OFS="\n" '{print $1, $2, $3, $4}' > outdir/five_prime/5cap_read_with_tag/${i}_with_TAG.fq
done



## 2. Trim TSO primer


for i in `ls outdir/five_prime/5cap_read_with_tag/`
do
	cutadapt -u 39 -j 40 -o outdir/five_prime/trim_TSO/${i}.trimed.remainGGG outdir/five_prime/5cap_read_with_tag/${i}
done


## 3. Mapping


for i in `ls outdir/five_prime/trim_TSO/`
do
        STAR --runThreadN 24 --genomeDir ${star_dir} --genomeLoad NoSharedMemory --readFilesIn outdir/five_prime/trim_TSO/${i} --outFileNamePrefix outdir/five_prime/mapping_outdir/${i}_ --outSAMtype SAM --outFilterMultimapNmax 1 --outFilterScoreMinOverLread 0.6 --outFilterMatchNminOverLread 0.6
done



## 4. convert to bed

#As `BED` format file can be used as input for `CAGEr` R package, we convert `SAM` to `BED`:


for i in `ls outdir/five_prime/mapping_outdir | grep "sam$"`
do
#### Add header and convert to bam
        samtools view -b -T ${fa_file} outdir/five_prime/mapping_outdir/${i} | samtools view -b >  outdir/five_prime/final_out/${i}_add_header.bam

#### Sort
        samtools sort outdir/five_prime/final_out/${i}_add_header.bam -o outdir/five_prime/final_out/${i}_add_header_sorted.bam

#### Build bam index for visualization
        samtools index outdir/five_prime/final_out/${i}_add_header_sorted.bam

#### Convert bam into bed
        bedtools bamtobed -i outdir/five_prime/final_out/${i}_add_header_sorted.bam > outdir/five_prime/final_out/${i}_add_header_sorted.bed
done



## 5. Remove reads mapped to tRNA and rRNA

#Reads that mapped at tRNA and rRNA position are discarded:

for i in `ls  outdir/five_prime/final_out |grep "bed$"`
do
        bedtools subtract -a outdir/five_prime/final_out/${i} -b reference/gencode_hg38_tRNA_rRNA_gene.bed > outdir/five_prime/final_out/${i%.*}_remove_trRNA.bed
done


## 6. find barcode and UMI

for i in `ls outdir/five_prime/final_out | grep "sorted_remove_trRNA.bed$"`
do
        python2 script/annotate_UMI_v1.py -N 16 -n 10 -F outdir/five_prime/fastq/${i%%_with*} -ID outdir/five_prime/final_out/${i} -O outdir/five_prime/annote/${i}.annote
done

mv outdir/five_prime/annote/*collapse outdir/five_prime/collapse/



## 7. collapse

for i in `ls outdir/five_prime/annote | grep "annote$"`
do
        Rscript script/collapse_UMI_TSS.R  outdir/five_prime/annote/${i}
done

mv outdir/five_prime/annote/*collapse outdir/five_prime/collapse/



## 8. change name

for i in `ls outdir/five_prime/collapse | grep "collapse$"`
do
        awk '{FS=" "}{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6}' outdir/five_prime/collapse/${i} > outdir/five_prime/collapse/${i}.6
        mv outdir/five_prime/collapse/${i}.6  outdir/five_prime/collapse/sampleTSS_TKD.bed
done



